# group_vars/all.yml
# Variables visible to all nodes
# pr011 Fileserver ( Samba, FTP)
---

#Samba traffic shoul pass through the rhbase_firewall_allow_services
rhbase_firewall_allow_services:
  - ftp
  - samba

#The netbios name of this server
samba_netbios_name: FILES

#When true, printers attached to the host are shared
samba_load_printers:
  - false

#Name of the server workgroup
samba_workgroup: AVALON

#Directories for the share are created under this directory
samba_shares_root: /srv/shares

#List of user groups that should be present.
rhbase_user_groups:
  - management
  - technical
  - sales
  - it

#List of dicts specifying users that should be present

rhbase_users:
  - name: stevenh
    comment: 'Steven Hermans'
    groups:
      - users
      - management
    password: '$6$9J5feMDP5KxcKAl4$OcGL8ePqFA64TFN5tTJ3mZLINxFWTJjIdUSPIdfg/f1sHywaaCYj64MlMIq7ndRxId47gF5btxGXQPPitUl7j/'
