# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_firewall_allow_services:
  - http
  - https


mariadb_databases:
  - name: wp_db

mariadb_root_password: fogMeHud8

mariadb_users:
  - name: wp_user
    password: CorkIgWac
    priv: 'wp_db.*:ALL'

wordpress_user: wp_user
wordpress_database: wp_db
wordpress_password: CorkIgWac


httpd_SSLCertificateFile: /etc/pki/tls/certs/pu004.crt
httpd_SSLCertificateKeyFile: /etc/pki/tls/private/pu004.key
