# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_repositories:
  - epel-release
rhbase_install_packages:
  - bash-completion
  - vim-enhanced
  - bind-utils
  - git
  - nano
  - tree
  - wget


rhbase_users:
  - name: tom
    comment: 'Tom Stechele'
    groups:
      - users
      - wheel



rhbase_motd: true
