# roles/rhbase/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: rhbase

- include: install.yml  # Install repositories and packages
- include: config.yml   # Configuration (/etc/)
- include: services.yml # Start/stop basic services
- include: security.yml # Security settings
- include: users.yml    # Create users
- include: admin.yml    # Admin user (a.o. SSH key)

