# site.yml
---
- hosts: all
  roles:
    - bertvv.rh-base



- hosts: pu001, pu002
  sudo: true
  roles:
    - bertvv.bind

- hosts: pr011
  sudo: true
  roles:
    - bertvv.samba
    - bertvv.vsftpd
  post_tasks:
    - name: ACL share Sales
      acl:
        path: /srv/shares/sales
        entity: management
        etype: group
        permissions: rx
        state: present
    - name: ACL share it
      acl:
        path: /srv/shares/it
        entity: management
        etype: group
        permissions: rx
        state: present
        




- hosts: pu004
  sudo: true
  pre_tasks:
    - name: copy key file
      copy:
        src: files/pu004.key
        dest: /etc/pki/tls/private/pu004.key
    - name: copy cert files
      copy:
        src: files/pu004.crt
        dest: /etc/pki/tls/certs/
  roles:
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress
